### ISSUE TITLE
needs version restraint on python

### ISSUE THREAD

**Issue by AaronOpfer** [conda-forge/pyjwt-feedstock#33]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

python 3.7 is not compatible with pyjwt 2.7 and above. pyjwt 2.8 _could_ work if `typing_extensions` is added, but it appears that pyjwt 2.9 dropped python 3.7 support entirely.
```
$ python -c 'import jwt'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/ctc/users/opfera/.conda/pyjwttest/lib/python3.7/site-packages/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/ctc/users/opfera/.conda/pyjwttest/lib/python3.7/site-packages/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/ctc/users/opfera/.conda/pyjwttest/lib/python3.7/site-packages/jwt/algorithms.py", line 7, in <module>
    from typing import TYPE_CHECKING, Any, ClassVar, Literal, NoReturn, cast, overload
ImportError: cannot import name 'Literal' from 'typing' (/ctc/users/opfera/.conda/pyjwttest/lib/python3.7/typing.py)
```

### Installed packages

```shell
# packages in environment at /ctc/users/opfera/.conda/pyjwttest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
openssl                   3.3.1                hb9d3cd8_3    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pyjwt                     2.9.0              pyhd8ed1ab_0    conda-forge
python                    3.7.12          hf930737_100_cpython    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
sqlite                    3.46.0               h6d4b2fc_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

### Environment info

```shell
$ conda info

     active environment : pyjwttest
    active env location : <snip>
            shell level : 2
       user config file : /home/opfera/.condarc
 populated config files : /etc/conda/condarc
                          /home/opfera/.condarc
          conda version : 24.5.0
    conda-build version : 24.5.1
         python version : 3.10.12.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=cascadelake
                          __conda=24.5.0=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /ctc/users/opfera/miniconda  (writable)
      conda av data dir : /ctc/users/opfera/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : <snip>
          package cache : <snip>
       envs directories : <snip>
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.10.12 Linux/3.10.0-1160.119.1.el7.x86_64 rhel/7.9 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : <snip>
             netrc file : None
           offline mode : False
```

**Comment by AaronOpfer** [comment]
I see that `meta.yaml` is already fixed. Can we patch the repodata also?

**Comment by AaronOpfer** [comment]
To be more clear:

pyjwt 2.7 and 2.8 can work with python 3.7 so long as typing_extensions is installed alongside,
pyjwt 2.9 does not work with python 3.7 at all.

**Comment by AaronOpfer** [comment]
I have submitted a repodata patch here:

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/835

**Comment by AaronOpfer** [comment]
Because `main` is fixed and the repodata patch is applied, I will close.
